name: Deploy Website

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build react
      uses: actions/setup-node@v3
      with:
        node-version: '14.5'
    - run: npm install
    - run: npm run build
    

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: pip3 install awscli
    - run: aws s3 sync ./build s3://skanddemo/
