name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@v2
        with:
          node-version: 15
    - uses: jeanlescure/react-deploy-to-s3-action@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        NODE_ENV: development # optional: defaults to production
        AWS_S3_BUCKET: skanddemo
        AWS_ACCESS_KEY_ID: AKIAWZAZQQHGXZAU3N5A
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: ap-southeast-2 # optional: defaults to us-east-1
        SOURCE_DIR: bundle # optional: defaults to public